export enum Region {
  Vinnychchyna = "Вінницька область",
  Volyn = "Волинська область",
  Dnipropetrovshchyna = "Дніпропетровська область",
  Donechchyna = "Донецька область",
  Zhytomyrshchyna = "Житомирська область",
  Zakarpattia = "Закарпатська область",
  Zaporizhzhia = "Запорізька область",
  IvanoFrankivshchyna = "Івано-Франківська область",
  CapitalKyiv = "КИЇВ",
  Kyivshchyna = "Київська область",
  Kirovohradschyna = "Кіровоградська область",
  Luhanshchyna = "Луганська область",
  Lvivshchyna = "Львівська область",
  Mykolayivshchyna = "Миколаївська область",
  Odeshchyna = "Одеська область",
  Poltavshchyna = "Полтавська область",
  Rivnenshchyna = "Рівненська область",
  Sumshchyna = "Сумська область",
  Ternopilshchyna = "Тернопільська область",
  Kharkivshchyna = "Харківська область",
  Khersonshchyna = "Херсонська область",
  Khmelnychchyna = "Хмельницька область",
  Cherkashchyna = "Черкаська область",
  Chernivechchyna = "Чернівецька область",
  Chernihivshchyna = "Чернігівська область",
}